services:
  # FastAPI application

  # Nginx Service 

  # PostgreSQL Service (pgvector)
  pgvector:
    image: pgvector/
  # Qdrant (VectorDB)

  # prometheus Monitoring 

  # Grafana Dashboard 

  # Node Exporter for system metrics 

  # PostgreSQL Exporter for Postgres metrics 




