services:
  # FastAPI application

  # Nginx Service 

  # PostgreSQL Service (pgvector)
  pgvector:
    image: pgvector/pgvector:latest
    container_name: pgvector
    ports: 
      - "5432:5432"
    volumes: 
      - 'pgvector:/var/lib/postgresql/data'
    env_file:
      - ./env/.env.postgres
    networks:
      - backend
    restart: always

    healthcheck:
      test: ["executable", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  
  # Qdrant (VectorDB)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - 'qdrant_data:/qdrant/storage'
    networks:
      - backend
    restart: always
  
  
  # prometheus Monitoring 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - backend
    restart: always




  # Grafana Dashboard 

  # Node Exporter for system metrics 

  # PostgreSQL Exporter for Postgres metrics 
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    ports:
      - "9187:9187"
    env_file:
      - ./env/.env.postgres_exporter
    depends_on:
      - pgvector
    networks:
      - backend
    restart: always




