services:
  # FastAPI application

  # Nginx Service 

  # PostgreSQL Service (pgvector)
  pgvector:
    image: pgvector/pgvector:latest
    container_name: pgvector
    ports: 
      - "5432:5432"
    volumes: 
      - 'pgvector:/var/lib/postgresql/data'

  # Qdrant (VectorDB)

  # prometheus Monitoring 

  # Grafana Dashboard 

  # Node Exporter for system metrics 

  # PostgreSQL Exporter for Postgres metrics 




